### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Cion318** [damiles/OpenCVGUI#5]
Hey, sorry for the dumb question, but how do you install this GUI ?
Would be awesome if you could link me some guide or maybe explain it.

Thx!

**Comment by AmberElferink** [comment]
Hey, in the README it says:
# Build
1. git submodule update --init --recursive
2. mkdir build
3. cd build
4. cmake ..
5. make
6. sudo make install

After that you can probably import it to your C++ project like any other.

That's alright if you use a cmake compiler for everything. However, I am using the Visual Studio compiler, so my cmake list is not compatible. Since I'm new at C++ and all the library importing and compiling concerned with it, this is quite the hassle. I tried downloading the prebuild option: [link to Release page](https://github.com/damiles/OpenCVGUI/releases/tag/0.1)
That's not the fully latest version though and it's only the x86 version, which is not compatible with my project.

I'm having so much issues, I would really give a lot for a precompiled x64 version right now, where I only have to fill in the include directory and lib file and it just works. I have been trying to get this library imported for 3 hours now without result. Going to find other options for a C++ OpenCV GUI.

**Comment by AmberElferink** [comment]
I just found out that this library is Linux only. Pity that it isn't mentioned on the page. Don't install it if you plan to use it on Windows folks :)

**Comment by damiles** [comment]
I think that is a bit late but exists a branch for window porting that is not updated and exists a release with libraries precompiled. Anyway, the project was obsoleted now, but if users continue interested in this library I will continue with the development.

**Comment by damiles** [comment]
I test it and works fine on linux, i'm going to try to re-compile on windows system
